apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: create-sbom
spec:

  steps:
    - name: create
      image: ghcr.io/ctron/batteries:1
      script: |
        #!/usr/bin/bash
        set -e
        cd /sboms
        curl -sSL https://raw.githubusercontent.com/ctron/bombastic-tekton-upload/main/examples/data/bom.json -o example-sbom.json

    - name: debug
      image: ghcr.io/ctron/batteries:1
      script: |
        find /sboms

  workspaces:
    - name: output
      description: The folder to scan SBOMs from
      mountPath: /sboms
