apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: send-sbom
spec:
  params:
    - name: sink-url
      type: string
      description: The URL of the sink endpoint
    - name: issuer-url
      type: string
      description: The issuer URL for retrieving an OIDC token for accessing the API
    - name: client-id
      type: string
      description: The ID for the OAuth2 client
    - name: client-secret
      type: string
      description: The secret for the OAuth2 client

  steps:
    - name: send
      image: ghcr.io/ctron/csaf-walker:0.6.0-alpha.3
      script: |
        #!/bin/sh
        
        # TODO: a step we should get rid of
        mkdir /upload/metadata
        echo '{"keys": []}' > /upload/metadata/metadata.json 
        
        sbom send /upload --oidc-issuer-url "$(params.issuer-url)" --oidc-client-id "$(params.client-id)" --oidc-client-secret "$(params.client-secret)" "$(params.sink-url)"

  workspaces:
    - name: input
      description: The folder to scan SBOMs from
      mountPath: /upload
